<?php
/**
 * Copyright (c) Zengliwei. All rights reserved.
 * Each source file in this distribution is licensed under OSL 3.0, see LICENSE for details.
 */

use CrazyCat\Email\Block\Adminhtml\System\Config\TestConnection;

/** @var $block TestConnection */
?>
<div data-mage-init='{"CrazyCat_Email/js/test-email": {
        "url": "<?= $block->escapeUrl($block->getDataByKey('ajax_url')) ?>",
        "button_label": "<?= $block->escapeJs(__('Test Email')) ?>",
        "sending_label": "<?= $block->escapeJs(__('Sending...')) ?>"
    }}'>
    <input type="text" class="input-text admin__control-text"
           id="<?= $block->escapeHtmlAttr($block->getDataByKey('html_id')) ?>"/>
    <p class="note"><?= $block->escapeHtml(__('You can try to send an email without saving config here.')) ?></p>
    <div style="margin-top:8px;">
        <button style="margin-right:8px;" type="button" class="scalable">
            <span><?= $block->escapeHtml(__('Test Email')) ?></span>
        </button>
    </div>
</div>
